var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                        o                       ",
   "                                                      xxxxx                o    ",
   "                                                    o x      x   xxxxx   xxxxxx ",
   "                                                  xxxxx      x!!!!!!!!!!!x      ",
   "                                                o x          xxxxxxxxxxxxx      ",
   "                                              xxxxx                             ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  xx                                   xxxxx                                    ",
   "  x                                                                             ",
   "  x            S       o     xxxxx                                              ",
   "  x          xxxx    xxxxx                 G                                    ",
   "  x  @   o   x  x!!!!x   x                      oo                          o   ",
   "  xxxxxxxxxxxx  x!!!!x   xxxxxxxx         xxxxxxxxxxxxxx   xxxxxxxx   xxxxxxxxxx",
   "                x!!!!x          x!!!!!!!!!x            x!!!!!!!!!!!!!!x         ",
   "                x!!!!x          x!!!!!!!!!x            x!!!!!!!!!!!!!!x         ",
   "                xxxxxx          xxxxxxxxxxx            x!!!!!!!!!!!!!!x         ",
   "                                                       xxxxxxxxxxxxxxxx         ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                            o                     ",
   "                                                                                           xxxx                   ",
   "                                                                        oo                                        ",
   "                                                                      xxxxx                          o            ",
   "                                                           xxx!!!!!!!!!!!!!!!!!!!!!xxx              xxx           ",
   "                                                           xxx!!!!!!!!!!!!!!!!!!!!!xxx         o                  ",
   "                                                           xxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxx                ",
   "                                                                                         o                        ",
   "                                                                                        xxxx                      ",
   "                                                               oooo              oo                               ",
   "                                                           xxxxxxxxxxxxx   xxxxxxxxxxx                            ",
   "         @                                                                                                        ",
   "    xxxxxxxx                                                             G                                        ",
   "    xxx                                            oo  S                                                          ",
   "    xxx                                           xxxxxx                                                          ",
   "    xxx                                           xxxxxx                                                          ",
   "    xxx              o                    o       xxxxxx            o                     o  G  o                 ",
   "    xxx           xxxxx G  xxx     G   xxxxxxx    xxxxxx         xxxxxx        xxxx      xxxxxxxxx                ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                              ",
   "   @                                          ",  
   "  xxxxxx                                      ",
   "  xxxxxx    o                                 ",
   "  xxxxxx                                      ",
   "  xxxxxx       o                              ",
   "  xxxxxx                                      ",
   "  xxxxxx           o                          ",
   "  xxxxxx                                      ",
   "  xxxxxx            S                         ",
   "  xxxxxx       o                              ",
   "  xxxxxx                                      ",
   "  xxxxxx        o                             ",
   "  xxxxxx                                      ",
   "  xxxxxx            o                         ",
   "  xxxxxx                                      ",
   "  xxxxxx                                      ",
   "  xxxxxx                                      ",
   "  xxxxxx             o                        ",
   "  xxxxxx                                      ",
   "  xxxxxx          o                           ",
   "  xxxxxx                                      ",
   "  xxxxxx       o                              ",
   "  xxxxxx                                      ",
   "  xxxxxx       o                              ",
   "  xxxxxx          o                           ",
   "  xxxxxx            o                         ",
   "  xxxxxx                                      ",
   "  xxxxxx             o                        ",
   "  xxxxxx                                      ",
   "  xxxxxx                                      ",
   "  xxxxxx                                      ",
   "  xxxxxx                                      ",
   "  xxxxxx                                      ",
   "  xxxxxx            o                         ",
   "  xxxxxx                                      ",
   "  xxxxxx                                      ",
   "  xxxxxx         o           o                ",
   "  xxxxxx     xxxxxxxxxx  G xxxx               ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx!xxx!xx!!!xx!xx!xxxxxxxxxxxxxxx",
   "xxxxxxxxxxx!x!xxx!x!xx!xx!xxxxxxxxxxxxxxx",
   "xxxxxxxxxxxx!xxxx!x!xx!xx!xxxxxxxxxxxxxxx",
   "xxxxxxxxxxxx!xxxx!!!xx!!!!xxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxx!xxxxxxxxx!xx!!!xx!!xxx!xxxxxxxxxx",
   "xxxxxxxx!xxx!xxx!xxxx!xxx!x!xx!xxxxxxxxxx",
   "xxxxxxxxx!x!x!x!xxxxx!xxx!xx!x!xxxxxxxxxx",
   "xxxxxxxxxx!xxx!xxxxx!!!xx!xxx!!xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
